import type {
  ClashData,
  Proposal,
  ResolutionOption,
  AuditEntry,
  Project,
  ConnectionStatus,
} from '@twinflux/shared-types';

export const mockProject: Project = {
  id: 'proj-001',
  name: 'Highway 401 Widening — Phase 2',
  location: 'Toronto, ON',
  clashSource: 'navisworks',
  constraints: {
    minCoverGravity: 1.2,
    minCoverPressure: 0.9,
    crossingClearance: 0.15,
    minSlopeGravity: 0.005,
    maxDepth: 6.0,
  },
  createdAt: '2025-11-15T08:00:00Z',
};

export const mockClashes: ClashData[] = [
  {
    id: 'CLH-001',
    source: 'navisworks',
    sourceRef: 'NW-GUID-001',
    testName: 'Pipes vs Pipes',
    type: 'hard',
    status: 'active',
    severity: 'critical',
    location: { x: 623450.25, y: 4834120.8, z: 185.35 },
    distance: -0.045,
    gridLocation: 'G-14',
    element1: {
      elementId: 'E-STM-001',
      modelFile: 'Storm_Network.dwg',
      discipline: 'Civil — Storm',
      category: 'Pipe',
      pipeNetworkName: 'STM-Main-01',
      networkType: 'gravity',
      pipeName: 'Storm Pipe S-101',
      pipeDiameter: 600,
      material: 'Reinforced Concrete',
      alignmentName: 'Storm-Main-AL',
      stationStart: 2448.5,
      stationEnd: 2452.3,
      invertElevation: 184.75,
      crownElevation: 185.35,
      slope: 0.008,
      cover: 1.45,
    },
    element2: {
      elementId: 'E-WTR-001',
      modelFile: 'Water_Network.dwg',
      discipline: 'Civil — Water',
      category: 'Pipe',
      pipeNetworkName: 'WTR-Dist-02',
      networkType: 'pressure',
      pipeName: 'Water Main W-205',
      pipeDiameter: 200,
      material: 'Ductile Iron',
      alignmentName: 'Water-Dist-AL',
      stationStart: 1205.0,
      stationEnd: 1208.5,
      invertElevation: 185.1,
      crownElevation: 185.3,
      slope: undefined,
      cover: 1.1,
    },
    detectedAt: '2025-12-01T14:30:00Z',
  },
  {
    id: 'CLH-002',
    source: 'acc',
    sourceRef: 'ACC-ISSUE-042',
    testName: 'Underground Utilities',
    type: 'clearance',
    status: 'active',
    severity: 'warning',
    location: { x: 623520.1, y: 4834095.4, z: 183.2 },
    distance: 0.08,
    gridLocation: 'H-18',
    element1: {
      elementId: 'E-SAN-001',
      modelFile: 'Sanitary_Network.dwg',
      discipline: 'Civil — Sanitary',
      category: 'Pipe',
      pipeNetworkName: 'SAN-Trunk-01',
      networkType: 'gravity',
      pipeName: 'Sanitary Trunk T-301',
      pipeDiameter: 450,
      material: 'PVC',
      alignmentName: 'San-Trunk-AL',
      stationStart: 3210.0,
      stationEnd: 3215.8,
      invertElevation: 182.75,
      crownElevation: 183.2,
      slope: 0.006,
      cover: 2.1,
    },
    element2: {
      elementId: 'E-FM-001',
      modelFile: 'ForceMains.dwg',
      discipline: 'Civil — Force Main',
      category: 'Pipe',
      pipeNetworkName: 'FM-PS2-01',
      networkType: 'pressure',
      pipeName: 'Force Main FM-102',
      pipeDiameter: 300,
      material: 'HDPE',
      alignmentName: 'FM-PS2-AL',
      stationStart: 845.2,
      stationEnd: 849.0,
      invertElevation: 183.05,
      crownElevation: 183.35,
      slope: undefined,
      cover: 1.35,
    },
    detectedAt: '2025-12-02T09:15:00Z',
  },
  {
    id: 'CLH-003',
    source: 'navisworks',
    sourceRef: 'NW-GUID-003',
    testName: 'Pipes vs Pipes',
    type: 'hard',
    status: 'resolved',
    severity: 'critical',
    location: { x: 623480.0, y: 4834110.0, z: 184.0 },
    distance: -0.12,
    gridLocation: 'G-16',
    element1: {
      elementId: 'E-STM-002',
      modelFile: 'Storm_Network.dwg',
      discipline: 'Civil — Storm',
      category: 'Pipe',
      pipeNetworkName: 'STM-Main-01',
      networkType: 'gravity',
      pipeName: 'Storm Pipe S-103',
      pipeDiameter: 600,
      material: 'Reinforced Concrete',
      alignmentName: 'Storm-Main-AL',
      stationStart: 2510.0,
      stationEnd: 2514.0,
      invertElevation: 183.4,
      crownElevation: 184.0,
      slope: 0.008,
      cover: 1.5,
    },
    element2: {
      elementId: 'E-WTR-002',
      modelFile: 'Water_Network.dwg',
      discipline: 'Civil — Water',
      category: 'Pipe',
      pipeNetworkName: 'WTR-Dist-02',
      networkType: 'pressure',
      pipeName: 'Water Main W-207',
      pipeDiameter: 150,
      material: 'Ductile Iron',
      alignmentName: 'Water-Dist-AL',
      stationStart: 1250.0,
      stationEnd: 1253.0,
      invertElevation: 183.8,
      crownElevation: 183.95,
      slope: undefined,
      cover: 1.05,
    },
    detectedAt: '2025-12-01T15:00:00Z',
  },
  {
    id: 'CLH-004',
    source: 'acc',
    sourceRef: 'ACC-ISSUE-055',
    testName: 'Underground Utilities',
    type: 'clearance',
    status: 'new',
    severity: 'warning',
    location: { x: 623500.0, y: 4834100.0, z: 182.5 },
    distance: 0.05,
    gridLocation: 'H-17',
    element1: {
      elementId: 'E-SAN-002',
      modelFile: 'Sanitary_Network.dwg',
      discipline: 'Civil — Sanitary',
      category: 'Pipe',
      pipeNetworkName: 'SAN-Trunk-01',
      networkType: 'gravity',
      pipeName: 'Sanitary Trunk T-305',
      pipeDiameter: 375,
      material: 'PVC',
      alignmentName: 'San-Trunk-AL',
      stationStart: 3250.0,
      stationEnd: 3255.0,
      invertElevation: 182.125,
      crownElevation: 182.5,
      slope: 0.005,
      cover: 1.8,
    },
    element2: {
      elementId: 'E-WTR-003',
      modelFile: 'Water_Network.dwg',
      discipline: 'Civil — Water',
      category: 'Pipe',
      pipeNetworkName: 'WTR-Dist-03',
      networkType: 'pressure',
      pipeName: 'Water Main W-310',
      pipeDiameter: 250,
      material: 'Ductile Iron',
      alignmentName: 'Water-Dist-AL',
      stationStart: 1300.0,
      stationEnd: 1303.5,
      invertElevation: 182.4,
      crownElevation: 182.65,
      slope: undefined,
      cover: 1.2,
    },
    detectedAt: '2025-12-03T11:00:00Z',
  },
];

export function generateOptions(clash: ClashData): ResolutionOption[] {
  const movementNeeded =
    clash.type === 'hard'
      ? Math.abs(clash.distance) + 0.15
      : 0.15 - clash.distance;

  const isE1Gravity = clash.element1.networkType === 'gravity';
  const isE2Gravity = clash.element2.networkType === 'gravity';
  let target = clash.element2;
  if (isE1Gravity && !isE2Gravity) target = clash.element2;
  else if (!isE1Gravity && isE2Gravity) target = clash.element1;
  else if ((clash.element1.pipeDiameter ?? 0) > (clash.element2.pipeDiameter ?? 0))
    target = clash.element2;
  else target = clash.element1;

  const offsetDown = movementNeeded + 0.05;
  const offsetUp = movementNeeded + 0.05;

  const newCoverDown = (target.cover ?? 1.5) + offsetDown;
  const newCoverUp = (target.cover ?? 1.5) - offsetUp;
  const newInvertDown = (target.invertElevation ?? 183) - offsetDown;
  const depthDown = (mockProject.constraints.maxDepth) - newCoverDown;

  return [
    {
      id: `${clash.id}-OPT-1`,
      label: 'OPT-1: Lower pipe',
      direction: 'lower',
      description: `Lower ${target.pipeName} by ${(offsetDown * 1000).toFixed(0)}mm`,
      offset: offsetDown,
      risk: newCoverDown < mockProject.constraints.maxDepth ? 'low' : 'medium',
      targetElement: target,
      affectedStationRange: [target.stationStart ?? 0, target.stationEnd ?? 0],
      resultingCover: parseFloat(newCoverDown.toFixed(3)),
      resultingClearance: parseFloat((movementNeeded + 0.05).toFixed(3)),
      resultingSlope: target.slope ?? null,
      downstreamImpactCount: target.networkType === 'gravity' ? 2 : 0,
      constraints: [
        {
          name: 'Min Cover',
          threshold: target.networkType === 'gravity' ? '≥ 1.200m' : '≥ 0.900m',
          actual: `${newCoverDown.toFixed(3)}m`,
          passed: newCoverDown >= (target.networkType === 'gravity' ? 1.2 : 0.9),
          message: newCoverDown >= (target.networkType === 'gravity' ? 1.2 : 0.9) ? 'OK' : 'Below minimum',
        },
        {
          name: 'Max Depth',
          threshold: '< 6.000m',
          actual: `${(newCoverDown + (target.pipeDiameter ?? 200) / 1000).toFixed(3)}m`,
          passed: true,
          message: 'OK',
        },
      ],
      warnings: target.networkType === 'gravity' ? ['Downstream propagation may be required'] : [],
    },
    {
      id: `${clash.id}-OPT-2`,
      label: 'OPT-2: Raise pipe',
      direction: 'raise',
      description: `Raise ${target.pipeName} by ${(offsetUp * 1000).toFixed(0)}mm`,
      offset: offsetUp,
      risk: newCoverUp >= (target.networkType === 'gravity' ? 1.2 : 0.9) ? 'low' : 'high',
      targetElement: target,
      affectedStationRange: [target.stationStart ?? 0, target.stationEnd ?? 0],
      resultingCover: parseFloat(Math.max(0, newCoverUp).toFixed(3)),
      resultingClearance: parseFloat((movementNeeded + 0.05).toFixed(3)),
      resultingSlope: target.slope ?? null,
      downstreamImpactCount: 0,
      constraints: [
        {
          name: 'Min Cover',
          threshold: target.networkType === 'gravity' ? '≥ 1.200m' : '≥ 0.900m',
          actual: `${Math.max(0, newCoverUp).toFixed(3)}m`,
          passed: newCoverUp >= (target.networkType === 'gravity' ? 1.2 : 0.9),
          message: newCoverUp >= (target.networkType === 'gravity' ? 1.2 : 0.9) ? 'OK' : 'Cover below minimum!',
        },
      ],
      warnings: newCoverUp < (target.networkType === 'gravity' ? 1.2 : 0.9)
        ? ['Cover will be below minimum — requires variance approval']
        : [],
    },
    {
      id: `${clash.id}-OPT-3`,
      label: 'OPT-3: Shift horizontal',
      direction: 'horizontal',
      description: `Shift ${target.pipeName} horizontally by ${(movementNeeded * 1000).toFixed(0)}mm`,
      offset: movementNeeded,
      risk: 'medium',
      targetElement: target,
      affectedStationRange: [target.stationStart ?? 0, target.stationEnd ?? 0],
      resultingCover: target.cover ?? 1.5,
      resultingClearance: parseFloat((movementNeeded).toFixed(3)),
      resultingSlope: target.slope ?? null,
      downstreamImpactCount: 0,
      constraints: [
        {
          name: 'ROW Boundary',
          threshold: 'Within ROW',
          actual: 'Within bounds',
          passed: true,
          message: 'OK',
        },
        {
          name: 'Utility Spacing',
          threshold: '≥ 300mm',
          actual: '450mm',
          passed: true,
          message: 'OK',
        },
      ],
      warnings: ['Requires spatial verification against adjacent utilities'],
    },
  ];
}

export const mockProposals: Record<string, Proposal> = {
  'CLH-001': {
    id: 'PROP-001',
    clashId: 'CLH-001',
    options: generateOptions(mockClashes[0]),
    selectedOptionId: null,
    consentState: 'options_ready',
    approvedBy: null,
    approvedAt: null,
    executedAt: null,
  },
  'CLH-002': {
    id: 'PROP-002',
    clashId: 'CLH-002',
    options: generateOptions(mockClashes[1]),
    selectedOptionId: null,
    consentState: 'options_ready',
    approvedBy: null,
    approvedAt: null,
    executedAt: null,
  },
};

export const mockAuditEntries: AuditEntry[] = [
  {
    id: 'AUD-001',
    timestamp: '2025-12-01T16:45:00Z',
    clashId: 'CLH-003',
    proposalId: 'PROP-003',
    optionApplied: 'OPT-1: Lower pipe',
    approvedBy: 'bim-coordinator@example.com',
    elementsModified: [
      {
        elementId: 'E-WTR-002',
        property: 'Invert Elevation',
        oldValue: '183.800',
        newValue: '183.480',
        unit: 'm',
      },
      {
        elementId: 'E-WTR-002',
        property: 'Crown Elevation',
        oldValue: '183.950',
        newValue: '183.630',
        unit: 'm',
      },
      {
        elementId: 'E-WTR-002',
        property: 'Cover',
        oldValue: '1.050',
        newValue: '1.370',
        unit: 'm',
      },
    ],
  },
];

export const mockConnection: ConnectionStatus = {
  agent: true,
  navisworks: true,
  civil3d: true,
  acc: false,
};
